version: "3.5"
services:
  api01: # API - Instância 01
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: "postgres://postgres:postgres@db:5432/rinhadb"
      REDIS_URL: "redis://redis"
    hostname: api01
    depends_on:
      - db
      - redis
    ports:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "0.4GB"

  api02: # API - Instância 01
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: "postgres://postgres:postgres@db:5432/rinhadb"
      REDIS_URL: "redis://redis"
    hostname: api02
    depends_on:
      - db
      - redis
    ports:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "0.4GB"

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "0.5GB"

  db: # Banco de dados
    image: postgres
    hostname: db
    environment:
      POSTGRES_DB: "rinhadb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: "0.9"
          memory: "1.4GB"

  redis: # Cache
    image: redis
    hostname: redis
    ports:
      - 6379:6379
    command: redis-server --save "" --appendonly no --maxclients 20000
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "0.3GB"

networks:
  default:
    driver: bridge
    name: rinha
